version: '3'
services:
  leaflet-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
